### ISSUE TITLE
Tag a release 

### ISSUE THREAD

**Issue by amellnik** [JuliaFEM/MiniBall.jl#15]
It seems like the package is in good shape and we've been using it in production for some time now.  Could we tag an initial release?

**Comment by ahojukka5** [comment]
Good idea. Btw, would you like to be a maintainer for this package?

**Comment by amellnik** [comment]
Sure!  This package seems like it's in great shape, but I can help with issues, documentation and so on.

**Comment by ahojukka5** [comment]
Nice to hear that. I think package's status is "mature", just needs some maintenance if syntax of Julia itself changes. Of course I will also be working with the package to keep it up to date. I set up attobot to help making new releases using browser.

**Comment by ovainola** [comment]
I'd be nice, if you'd continue to maintain the package! Documentation is quite limited, due to my laziness. I can make a new tag this weekend.

**Comment by ovainola** [comment]
tagged v0.0.2, pull request in https://github.com/JuliaLang/METADATA.jl/pull/12433

**Comment by TeroFrondelius** [comment]
```julia
julia> Pkg.add("Miniball")
INFO: Cloning cache of Miniball from https://github.com/JuliaFEM/Miniball.jl.git
INFO: Installing Miniball v0.0.1
INFO: Building Miniball
```
What is the status? Above Metadata pull request is closed, but still the current version of Miniball.jl is v0.0.1.  Clearly new tag v0.1.0 has not been through.

**Comment by amellnik** [comment]
I think it was closed without merging -- I'll submit another later today.

**Comment by amellnik** [comment]
New pull request open at https://github.com/JuliaLang/METADATA.jl/pull/12638

**Comment by amellnik** [comment]
Closed via https://github.com/JuliaLang/METADATA.jl/pull/12638 -- freeing Miniball and updating should now install the 0.1.1 release.

**Comment by ahojukka5** [comment]
@amellnik, just for curiosity, in what kind of application do you use Miniball.jl in production..?

**Comment by amellnik** [comment]
It's part of an optimization step where we determine how to position the dies within a wafer for a product.
