### ISSUE TITLE
miniball does not contain all points

### ISSUE THREAD

**Issue by jw3126** [JuliaFEM/MiniBall.jl#19]
The miniball does not always contain all points, even when adding a 1% margin. See #18 for examples.

**Comment by ahojukka5** [comment]
#18 is merged, can we close this?

**Comment by jw3126** [comment]
Well #18 is only tests, the bug still exists.

**Comment by jw3126** [comment]
I think we should add a check to the `miniball` function itself, that the ball contains indeed all points. I can provide a PR for that. On top of that it would be nice to include Bernds fixes at some point. At the moment I do not understand the code at all, so I cannot provide a PR for that. At least not anytime soon.

**Comment by jw3126** [comment]
I added a check #23

**Comment by TeroFrondelius** [comment]
@jw3126 can you try with Cxx version if the C++ implementation passes all the tests now? @ahojukka5 can you call @ovainola and ask if he has any interests fixing this.

**Comment by TeroFrondelius** [comment]
# Deprecated
This repo has some nasty bug, see broken tests. After bug hunt a decission to refactor led to the rewriting of the package, which gave the opportunity to change the license. Development continues in  [BoundingSphere.jl](https://github.com/JuliaFEM/BoundingSphere.jl). Use that package instead.

**Comment by jw3126** [comment]
Yes I would also do `v0.2.0`.
