### ISSUE TITLE
Add MiniBall.jl README to www.juliafem.org

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaFEM/MiniBall.jl#2]
I think we should add README (the current documentation) to www.juliafem.org.

**Comment by TeroFrondelius** [comment]
Hi @amellnik,
If you would like to find something easy to start with, please fix the documentation such away that this would show some content: https://juliafem.github.io/Miniball.jl/latest. Here is an example: https://github.com/JuliaFEM/ModelReduction.jl/tree/master/docs and ping @ahojukka5 if you will need some help.

**Comment by amellnik** [comment]
Documentation now appears at http://juliafem.org/Miniball.jl/latest/ and should build automatically in the future.

**Comment by amellnik** [comment]
One minor note is that the next time we tag a release we should remember to add a 'stable' version of the docs badge to the main readme.

**Comment by TeroFrondelius** [comment]
Hi @amellnik,
I think that according to the standard version numbering patch version number can be used to add the 'stable' docs badge. If you think about it, it's kind of a bug fix. You found a bug that one badge status is incorrect and now you will release a new patch version.

**Comment by amellnik** [comment]
Good point -- I'll add the other badge and tag a minor release tomorrow.

**Comment by amellnik** [comment]
And done -- Travis CI is pretty magical.
