### ISSUE TITLE
Version 1.0.0 release plan

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaFEM/MiniBall.jl#24]
I think this package could be a perfect example of moving to version 1.0.0. I think at least these things should be done to have the 1.0.0 version:

- [ ] Julia v1.0.0
- [ ] Depreciation warnings fix
- [ ] Fix the #19 bug
- [ ] documentation
- [ ] User Interface, mainly output

**Comment by ahojukka5** [comment]
What about documentation?

**Comment by TeroFrondelius** [comment]
Yes, definitely. I added documentation to the list.

**Comment by jw3126** [comment]
For `1.0.` I would prefer that the `miniball` function returns something other then `MBContainer`. Maybe just a tuple center and radius or a `Ball` struct that contains these. `MBContainer` is an implementation detail, it may be altered, if the algorithm changes. Therefore user code should not be build around it. If someone wants to access `MBContainer` this should be through some non exported function I think.

**Comment by TeroFrondelius** [comment]
I agree user interface should be lean and clean. Also, pretty printing would be a nice feature to have. @jw3126 can you take charge of the user interface development?

**Comment by jw3126** [comment]
@TeroFrondelius sure!

**Comment by jw3126** [comment]
I don't think there is an easy way to check optimialty, but I agree it would be very desirable!
A heursitic would be to randomly pertrub the center and see if it has smaller cost (= maximum square distance to the point cloud).

**Comment by ahojukka5** [comment]
Well, [here](http://hbf.github.io/miniball/seb.pdf) is the original article describing algorithm. It is hard to find connection between the mathematics and (a current) implementation. At least we should check that all the points are inside the sphere.

**Comment by jw3126** [comment]
We currently do check that all points are inside the sphere. One way to check optimality is the following:

A feasible ball is optimal if and only if its center is contained in the convex hull of the points on the boundary. We could compute the distance between `center` and this convex hull. For example `gjk` algorithm could do this https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/src/gjk.jl.

But thats quite a lot of machinery, more then the miniball algorithm itself...

**Comment by TeroFrondelius** [comment]
# Deprecated
This repo has some nasty bug, see broken tests. After bug hunt a decission to refactor led to the rewriting of the package, which gave the opportunity to change the license. Development continues in  [BoundingSphere.jl](https://github.com/JuliaFEM/BoundingSphere.jl). Use that package instead.
